server:
  #port: ${port:10086}
  port: 10086
spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      # eureka 服务地址，如果是集群的话；需要指定其它集群eureka地址
      #defaultZone: ${defaultZone:http://127.0.0.1:10086/eureka}
      defaultZone: http://127.0.0.1:10086/eureka
      # 不注册自己，默认是true，如果是集群搭建需要注册自己
    register-with-eureka: false
      # 不拉取服务,默认是true，集群要为true
    fetch-registry: false
  server:
    #服务失效剔除时间，默认60秒（以毫秒为单位）
    eviction-interval-timer-in-ms: 3000
    #关闭自我保护模式（默认是打开的）
    enable-self-preservation: false
