server:
  port: 10010

spring:
  application:
    name: spring-gateway
  #配置网关
  cloud:
    gateway:
      routes:
        #id可以任意
        - id: user-service-route
        #代理的服务地址
          #uri: http://127.0.0.1:9091
          uri: lb://user-service #lb是LoadBalance（负载均衡）的简写
        #路由断言：可以匹配映射地址
          predicates:
            #- Path=/user/**
            #- Path=/**
            - Path=/api/user/**
          filters:
            # 添加前期路径前缀（和Path结合）
            #- PrefixPath=/user #http://localhost:10010/2 -> http://localhost:9091/user/2

            # 去除路径前缀，1表示去一个，2表示去两个，以此类推（和Path结合）
            - StripPrefix=1 #http://localhost:10010/api/user/2 -> http://localhost:9091/user/2
            - MyParam=name #自定义的局部过滤器
      #默认过滤器，会对所有路由都生效
      default-filters:
        - AddResponseHeader=X-Response-Foo,Bar #头名称和值可以自定义
        - AddResponseHeader=MyKey,Hello
      #跨域请求处理
      globalcors:
        corsConfigurations:
          '[/**]':
            #allowedOrigins: * # 这种写法或者下面的都可以，*表示全部
            allowedOrigins:
              - "http://docs.spring.io"
            allowedMethods:
              - GET

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true

